// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDodgXxy6efYc20GdodoW0JogT5jWCQNI',
    appId: '1:1078485876873:web:3141b9cfb89eda4af24658',
    messagingSenderId: '1078485876873',
    projectId: 'panara-7a588',
    authDomain: 'panara-7a588.firebaseapp.com',
    storageBucket: 'panara-7a588.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzuYCFTUX0LRzR1FArA2STlMUDh8lduis',
    appId: '1:1078485876873:android:168162392653a0dff24658',
    messagingSenderId: '1078485876873',
    projectId: 'panara-7a588',
    storageBucket: 'panara-7a588.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrWf10j17fGTovd3CQW5eJdq0CICbqNmc',
    appId: '1:1078485876873:ios:a89749734caa5e72f24658',
    messagingSenderId: '1078485876873',
    projectId: 'panara-7a588',
    storageBucket: 'panara-7a588.appspot.com',
    iosClientId: '1078485876873-e6bedj9ad5q8u0mj60oi7bherln6rg3u.apps.googleusercontent.com',
    iosBundleId: 'com.example.panaraStudios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrWf10j17fGTovd3CQW5eJdq0CICbqNmc',
    appId: '1:1078485876873:ios:60b467e2067b13fbf24658',
    messagingSenderId: '1078485876873',
    projectId: 'panara-7a588',
    storageBucket: 'panara-7a588.appspot.com',
    iosClientId: '1078485876873-dba1dmucl4s2afud9gtsqilakhfsv6ql.apps.googleusercontent.com',
    iosBundleId: 'com.example.panaraStudios.RunnerTests',
  );
}
